### ISSUE TITLE
Fountains (in "UtilitiesPoly") are not showing own the map unless highlighted.

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rio#128]
https://basecamp.com/1741364/api/v1/projects/2809857/todos/234704332.json

**Comment by davidheyman** [comment]
@bcsheesley: Looks like we never updated this query. The new one for Fountains should be:

```
SELECT * FROM basepoly WHERE stylename = 'fountains' AND firstdispl <= 2013 AND lastdispla >= 2013
```

We'll want to do the polygon + point (like with parks) for this but perhaps only display the polygon when it is at the highest zoom level.

**Comment by bcsheesley** [comment]
Thanks. These updates sit between the `buildings` and `railpoint` layers in the xml.

[fountains.xml.zip](https://github.com/axismaps/rio/files/131460/fountains.xml.zip)

The icon is displayed up until the highest zoom level, at which point it switches to a polygon + label, like this:

![z17](https://cloud.githubusercontent.com/assets/4501388/13060182/47788b40-d3f5-11e5-9f2c-290d02aeac16.png)

![z18](https://cloud.githubusercontent.com/assets/4501388/13060186/4e5e2816-d3f5-11e5-91f3-a91baf78055f.png)
