### ISSUE TITLE
Names of feature types in "PublicSpacesPoly" should also show on the map (e.g., Parks, Squared, Gardens, Cemeteries)

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rio#129]
https://basecamp.com/1741364/api/v1/projects/2809857/todos/234708546.json

**Comment by bcsheesley** [comment]
There were edits to both the labels and polygon styles for these public spaces layers. I've attached the updates here. Let me know if this goes in okay and I'll check the new tiles to make sure it looks right.

Polygons:
The stuff in public_spaces.xml goes between `marshes` and `ponds-outline`.

Labels:
The stuff in public_spaces_labels.xml goes between `neighborhoods_labels` and `roads_labels-low`.

[public_spaces_labels.xml.zip](https://github.com/axismaps/rio/files/131449/public_spaces_labels.xml.zip)

[public_spaces.xml.zip](https://github.com/axismaps/rio/files/131450/public_spaces.xml.zip)
