### ISSUE TITLE
Timeline tick marks are not regularly spaced

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rio#153]

**Comment by kingfisher13** [comment]
@davidheyman What do you mean here? Are you referring to the last 2 lines of the timeline? That's the gap between 2000 and 2009. Or did you mean a different grid?

**Comment by davidheyman** [comment]
That last one at the end is definitely the problem. Let's just remove it.

There also aren't enough grid lines. Can you bring the minor tick marks back and make them the same height as the major tick marks?
