### ISSUE TITLE
Viewshed points should show viewshed cone on first tap and show full image when tapped again

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rio#161]

**Comment by kingfisher13** [comment]
@davidheyman I think this is working as intended now. I had to a little workaround as Leaflet doesn't differentiate between clicks and taps. 

Also, I hid the probe on mobile for now. Do you want that showing?

**Comment by davidheyman** [comment]
This is looking good. The only change I'd make would be to hide the viewshed once the user taps anywhere else (especially another point).
