### ISSUE TITLE
[Mobile] Ensure mobile interface loads on iPhone 6+

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rio#176]

**Comment by kingfisher13** [comment]
@davidheyman How do you want me to do this? I don't have an iPhone. Is testing via computer enough here?

**Comment by davidheyman** [comment]
Check the media queries against this (or something similar) -> http://stackoverflow.com/questions/25759046/iphone-6-and-6-plus-media-queries <http://stackoverflow.com/questions/25759046/iphone-6-and-6-plus-media-queries>

After that, we’ll have to just send it to the client (who has one) to test

**Comment by davidheyman** [comment]
Thinking more about how it was relayed to me, it was a “sometimes” bug. I’m wondering if there are situations where that resize event doesn’t fire.

**Comment by kingfisher13** [comment]
Have them try that. It matches both the mobile CSS and the mobile JS to `device-max-width` which should handle high-resolution pixel devices better.
