### ISSUE TITLE
iPad should use desktop version of site instead of mobile

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rio#181]

**Comment by kingfisher13** [comment]
@davidheyman iPad portrait is still mobile sizing. Should I drop it down even further to account for that? Or just leave it such that iPad portrait is mobile, but iPad landscape is Desktop?

**Comment by davidheyman** [comment]
I think they both should be desktop if possible as long as:

1. Everything fits on the screen (legend and probe results)
2. It doesn’t mess up breakpoints for big-ass phones
