### ISSUE TITLE
Portuguese header broken

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rio#183]
![Jul-12-2017 21-24-15](http://static.gitscout.com/04a62b77653c17232aaaf1b1c44eadb7a8b1375d2ae99681594ddac5d2e11d59.gif)

**Comment by kingfisher13** [comment]
@davidheyman This is going to need Portugese translations for those English text snippets. But they are now supported.

**Comment by fdahdah** [comment]
Portuguese titles for Header buttons (that get revealed on mouseover) should be as follows: "Compartilhar no Facebook"; "Postar no Twitter"; "Exportar imagem do mapa"; "Galeria de imagens"; "Mais informações"
